version: '3'
services:
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ${PHP_WEBROOT}:/var/www/html
        links:
            - php-fpm
            - mysql
            - mail
    php-fpm:
        container_name: php-fpm
        volumes:
            - ${PHP_WEBROOT}:/var/www/html
        links:
            - mail
            - mysql
    php-cli:
        container_name: php-cli
        links:
            - mail
            - mysql
    mysql:
        build: mysql
        container_name: mysql
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_USER_PASS}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    mail:
        
volumes:
    mysql_data:
        driver: local