version: '3'
services:
    php-fpm:
        build: ./php-fpm/production
    mail:
        image: tvial/docker-mailserver:latest
        hostname: mail
        domainname: domain.com
        container_name: mail
        ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
        volumes:
            - maildata:/var/mail
            - mailstate:/var/mail-state
            - ./mail/production/config/:/tmp/docker-mailserver/
        environment:
            - ENABLE_SPAMASSASSIN=1
            - ENABLE_CLAMAV=1
            - ENABLE_FAIL2BAN=1
            - ENABLE_POSTGREY=1
            - ONE_DIR=1
            - DMS_DEBUG=0
        cap_add:
            - NET_ADMIN