version: '3'
services:
    mail:
        build: ./mail/production
        hostname: mail
        domainname: domain.com
        container_name: mail
        environment:
            MAIL_DOMAIN: domain.com
            SENDER_HOST: php-fpm.docker_default
            CERT_COUNTRY: COUNTRY
            CERT_STATE: CITY
            CERT_CITY: CITY
            CERT_COMPANY: COMPANY
            CERT_DOMAIN: domain.com
        ports:
            - "25:25"
        volumes:
            - mail_data:/var/lib/postfix
            - mail_quene_data:/var/spool/postfix
            - dkim_db:/var/db/dkim
volumes:
    mail_data:
        driver: local
    mail_quene_data:
        driver: local
    dkim_db:
        driver: local